#!/usr/bin/env bash
#hello world 

PID_FILE="/tmp/myscript.pid"

echo $$ > "$PID_FILE"

cleanup() {
  rm -f "$PID_FILE"
  exit 0
}

trap 'echo "Y U no love me?!";' SIGINT
trap 'echo "I hate the kill command";' SIGTERM
trap 'cleanup' SIGQUIT SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

